# Generated by Django 4.2.7 on 2023-11-10 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
