# Generated by Django 4.2.7 on 2023-11-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0004_tasks_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
