# Generated by Django 4.2.7 on 2023-11-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0006_remove_tasks_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
